config/routes.rb
Rails.application.routes.draw do
  get 'say/hello'

  get 'say/goodbye'

  get 'say/filenames'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/say_controller.rb
class SayController < ApplicationController
  def hello
  	@time = Time.now
  end
  def goodbye
  end
  def filenames
  	@files = Dir.glob('*')
  	return @files
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/imput_helper.rb
module ImputHelper
end

app/helpers/say_helper.rb
module SayHelper
end

app/helpers/user_imput_helper.rb
module UserImputHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Demo</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/say/filenames.html.erb
<h1>Files in the current directory</h1>
<p>
	The files in the current directory
</p>
<ul>
	<% for file in @files %>
	<li><%= file; %></li>
	<% end %>
</ul>

app/views/say/goodbye.html.erb
<h1>Goodbye!</h1>
<p>It was nice having you here.</p>
<p>
	Say <%= link_to "Hello", say_hello_path %> again.
</p>

app/views/say/hello.html.erb
<h1>Hello from Rails!</h1>
<p>
	It is now <%= @time %>
</p>
<p>
	Time to say
	<%= link_to "Goodbye", say_goodbye_path %>!
</p>
<p>
	Time to do the math!
	<%= 1+2 %> 
</p>